Refactor core API based on Pydantic models and direct loading from external sources
maykinmedia/django-setup-configuration pull request #18
Opened 2024-11-14 16:13 UTC by swrichards

Based on discussions related both to PodiumD integration and broader lessons learned with regards to configuration management, this PR implements the first (big) iteration on the new design: step configs are loaded directly from external sources and are fully typed and validated using Pydantic.

This PR has removed two hooks from the API (the configuration check, and the self test), not because they are not important, but because such "liveness" and "health" checks arguably belong elsewhere. Documentation generation and multi-file yaml sources will be implemented in an upcoming iteration.

2024-11-15 09:53 UTC, stevenbal requested changes
Looks good overall! Some minor remarks/questions

2024-11-15 09:53 UTC, stevenbal commented on tests/test_runner.py
> +    return StepExecutionResult(
Is this test necessary? Since the test below it probably tests the same initialization but also executes the step?

2024-11-15 09:53 UTC, stevenbal commented on tests/test_runner.py
> +        )
Maybe you could instantiate a new `StepExecutionResult` instead of replacing something on the `succesful` fixture

2024-11-15 09:53 UTC, stevenbal commented on tests/test_runner.py
> +def test_already_configured_steps_are_not_run_when_overwrite_is_false(
I might have overlooked it, but I think you're missing a test that verifies that already configured steps are run again when overwrite=True

2024-11-15 09:53 UTC, stevenbal commented on django_setup_configuration/config_settings.py
> +class ConfigSettings(Generic[TConfigModel]):
This is only for the generate documentation command right? There is probably some work to do here still to make it work, might be good to add a TODO for it or refer to it in another issue

2024-11-19 12:47 UTC, stevenbal commented on django_setup_configuration/test_utils.py
> +    step: BaseConfigurationStep, yaml_file_path: str | None = None
I seem to be getting typing errors here:

```python
def get_config_model(path):
    return load_step_config_from_source(ObjectsAPIConfigurationStep, path)
```


```Argument of type "type[ObjectsAPIConfigurationStep]" cannot be assigned to parameter "step" of type "BaseConfigurationStep[Unknown]" in function "load_step_config_from_source"
  "type[ABCMeta]" is not assignable to "type[BaseConfigurationStep[Unknown]]
```

Similarly, when using `step.execute(model)`, I also get typing errors:

```
Argument of type "ConfigurationModel" cannot be assigned to parameter "model" of type "ObjectsAPIGroupConfigModel" in function "execute"
  "ConfigurationModel" is not assignable to "ObjectsAPIGroupConfigModel"
```

2024-11-21 14:44 UTC, stevenbal commented on django_setup_configuration/test_utils.py
> +    step: BaseConfigurationStep, yaml_file_path: str | None = None
No longer getting errors :+1:

2024-11-22 08:37 UTC, sergei-maertens commented on README.rst
> +* Django 3.2 or above
What's the reason django 3.2 still needs to be supported? It's been EOL for a while

2024-11-22 08:37 UTC, sergei-maertens commented on README.rst
> +        is_staff: Optional[int] = DjangoModelRef("auth.User", "username", default=0)
Can we replace Optional with the more idiomatic `| None` syntax? Or do we need to support ancient python versions?

2024-11-22 08:37 UTC, sergei-maertens commented on django_setup_configuration/configuration.py
> +            step
enable_flag? enable_trigger?

2024-11-25 14:25 UTC, stevenbal commented on tox.ini
> +    py{310,311,312}-django{32,42}-pydantic{20,29}
```suggestion
    py{310,311,312}-django{32,42}-pydantic{20,210}
```

2024-11-25 14:35 UTC, merged